version: "3.4"
services:
  user-api:
    build:
      context: ./Microservices/UserApi
      dockerfile: Dockerfile
    ports:
      - 9011:80
    depends_on:
      - database

  product-api:
    build:
      context: ./Microservices/Aspect.ProductAPI
      dockerfile: Dockerfile
    ports:
      - 9012:80
    depends_on:
      - database

  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aspect
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
